### ISSUE TITLE
Proxyscan blacklist segfault

### ISSUE THREAD

**Issue by ManiacTwister** [shalture/shalture#49]
Hello,

(This issue is based on https://github.com/shalture/shalture-contrib-modules/issues/1)

If a user is listed in two or more configured blacklists the proxyscan/dnsbl crashes services because it tries to kline the user (which is already disconnected) again. Here is the corresponding backtrace.

```
Program terminated with signal 11, Segmentation fault.
#0  bs_notice (from=0xc39660 "OperServ", target=0x0, fmt=<optimized out>) at main.c:127
127		if (*target == '#' && !strcmp(from, chansvs.nick))
(gdb) bt
#0  bs_notice (from=0xc39660 "OperServ", target=0x0, fmt=<optimized out>) at main.c:127
#1  0x0000032a9f851c19 in dnsbl_hit (blptr=0xc66e60, u=0x32ab9c8ef70) at dnsbl.c:504
#2  blacklist_dns_callback (vptr=<optimized out>, reply=<optimized out>) at dnsbl.c:346
#3  0x0000032ab9408c99 in res_read_single_reply (F=<error reading variable: Unhandled dwarf expression opcode 0xfa>) at res.c:854
#4  0x0000032ab9408d13 in res_readreply (cptr=0xbee5c0) at res.c:870
#5  0x0000032ab966050b in mowgli_epoll_eventloop_select (eventloop=0x32ab9ca1f70, delay=<optimized out>) at epoll_pollops.c:188
#6  0x0000032ab9661515 in mowgli_simple_eventloop_timeout_once (eventloop=0x32ab9ca1f70, timeout=0) at null_pollops.c:55
#7  0x0000032ab9660b4c in mowgli_eventloop_run_once (eventloop=0x32ab9ca1f70) at eventloop.c:129
#8  0x0000032ab940a26f in io_loop () at send.c:77
#9  0x0000032ab93f009b in shalture_main (argc=<optimized out>, argv=0x3ff22fefc88) at atheme.c:451
#10 0x0000032ab906bead in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x00000000004005f1 in _start ()
```

Log Message:
```
[2015-02-23 16:03:46] user_add(): efiii (~bla@tor-exit.kakapo.dk) -> bla.tld
[2015-02-23 16:03:46] DNSBL: k-lining efiii!~bla@tor-exit.kakapo.dk [irssi] who is listed in DNS Blacklist rbl.efnetrbl.org.
[2015-02-23 16:03:46] <- :00AAAAAAJ NOTICE 42XAAAABO :Your IP address 82.211.223.3 is listed in DNS Blacklist rbl.efnetrbl.org
[2015-02-23 16:03:46] <- :00AAAAAAJ ENCAP * KLINE 86400 * tor-exit.kakapo.dk :Banned (DNS Blacklist)
[2015-02-23 16:03:46] -> :42X NOTICE 00AAAAAAJ :Added temporary 1440 min. K-Line [*@tor-exit.kakapo.dk]
[2015-02-23 16:03:46] -> :42XAAAABO QUIT :K-Lined
[2015-02-23 16:03:46] m_quit(): user leaving: efiii
[2015-02-23 16:03:46] user_delete(): removing user: efiii -> bla.tld (K-Lined)
[2015-02-23 16:03:46] DNSBL: k-lining (null)!(null)@(null) [(null)] who is listed in DNS Blacklist 6667.1.0.0.127.ip-port.exitlist.torproject.org.

```

A working quick fix can be found here: https://gist.github.com/ManiacTwister/4a8ba388fa84f63b08bb#file-shalture-dnsbl-patch

**Comment by ManiacTwister** [comment]
Any news? :)

**Comment by ilbelkyr** [comment]
Sorry for the delay.
At a glance, it looks like the user has already been freed from the user heap; the memory might have been reused for another user at that point, if I'm not mistaken. (For the cases where your fix works, that obviously isn't the case, but I'd prefer a fix that actually avoids this pitfall.)
